sonar.projectKey=tec-eli_rustebra
sonar.organization=tec-eli
sonar.projectName=rustebra
sonar.sources=src
sonar.tests=tests

sonar.rust.clippy.enabled=false
sonar.rust.clippy.reportPaths=clippy-report.json
sonar.rust.lcov.reportPaths=lcov.info
